name: Test that tutorial runs on latest colab image

on:
  push:
  schedule:
    - cron: '0 2 3 * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest-4core # increase disk space  
    # https://console.cloud.google.com/artifacts/docker/colab-images/europe/public/runtime
    container:
      image: europe-docker.pkg.dev/colab-images/public/runtime:latest
    steps:
      - uses: actions/checkout@v4
      - name: Dev - Install njab (from branch) - optional
        if: github.event_name == 'push'
        run: |
          echo GITHUB_REF= $GITHUB_REF
          echo GITHUB_SHA= $GITHUB_SHA
          echo "Branch or Tag: ${{ github.ref }}"
          pip install .
          # pip install git+https://github.com/RasmussenLab/njab.git@$GITHUB_SHA
          cd docs
          echo
          echo Installed version of njab:
          python3 -c "import njab; print(njab.__version__)"
      - name: Test tutorials
        run: | 
          python3 -m pip install papermill ipykernel njab
          cd docs/tutorial
          papermill explorative_analysis.ipynb --help-notebook
          papermill log_reg.ipynb --help-notebook
          papermill log_reg.ipynb log_reg_tested.ipynb
          papermill explorative_analysis.ipynb explorative_analysis_tested.ipynb

